name: neuron
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  
  - tensorflow==2.18.0
  - keras==3.6.0
  - pandas==2.2.0
  - numpy==1.26.3
  - matplotlib==3.8.2
  - scikit-learn==1.4.0
  - rdkit==2025.9.3